use_frameworks!

target 'LGPromptViewModule_Example' do
  pod 'LGPromptViewModule', :path => '../'

  target 'LGPromptViewModule_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
